# Translations template for fb_vmware.
# Copyright (C) 2022 Frank Brehm, Berlin
# This file is distributed under the same license as the fb_vmware project.
# Frank Brehm <frank@brehm-online.com>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: fb_vmware 0.4.1\n"
"Report-Msgid-Bugs-To: frank@brehm-online.com\n"
"POT-Creation-Date: 2022-05-30 12:44+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <frank@brehm-online.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.1\n"

#: lib/fb_vmware/about.py:282 lib/fb_vmware/cluster.py:370 lib/fb_vmware/controller.py:266
#: lib/fb_vmware/datastore.py:225 lib/fb_vmware/dc.py:161 lib/fb_vmware/disk.py:388
#: lib/fb_vmware/ds_cluster.py:129 lib/fb_vmware/ether.py:501 lib/fb_vmware/host.py:249
#: lib/fb_vmware/host.py:673 lib/fb_vmware/host_port_group.py:198 lib/fb_vmware/network.py:140
#: lib/fb_vmware/vm.py:631
msgid "The given parameter {p!r} on calling method {m}() has failing attributes"
msgstr ""

#: lib/fb_vmware/about.py:290 lib/fb_vmware/cluster.py:281 lib/fb_vmware/dc.py:169
#: lib/fb_vmware/disk.py:397
msgid "Parameter {t!r} must be a {e} object, a {v} object was given instead."
msgstr ""

#: lib/fb_vmware/about.py:303 lib/fb_vmware/cluster.py:306 lib/fb_vmware/controller.py:308
#: lib/fb_vmware/datastore.py:265 lib/fb_vmware/dc.py:189 lib/fb_vmware/disk.py:419
#: lib/fb_vmware/ds_cluster.py:155 lib/fb_vmware/ether.py:466 lib/fb_vmware/host.py:281
#: lib/fb_vmware/host.py:591 lib/fb_vmware/host_port_group.py:222 lib/fb_vmware/network.py:172
#: lib/fb_vmware/vm.py:510
msgid "Creating {} object from:"
msgstr ""

#: lib/fb_vmware/about.py:339 lib/fb_vmware/controller.py:313 lib/fb_vmware/disk.py:424
#: lib/fb_vmware/ether.py:471 lib/fb_vmware/host_port_group.py:227 lib/fb_vmware/vm.py:581
msgid "Created {} object:"
msgstr ""

#: lib/fb_vmware/base.py:223
msgid "Connecting to vSphere host {h}:{p} as {u!r} ..."
msgstr ""

#: lib/fb_vmware/base.py:241
msgid "Disconnecting from vSphere host {}."
msgstr ""

#: lib/fb_vmware/base_config.py:157
msgid "An empty name for a VSPhere datacenter is not allowed."
msgstr ""

#: lib/fb_vmware/base_config.py:171
msgid "An empty user name for connecting to a VSPhere datacenter is not allowed."
msgstr ""

#: lib/fb_vmware/base_config.py:263
msgid "Unknown key {k!r} with value {v!r} for VSphere {vs!r} in section {sec!r} found."
msgstr ""

#: lib/fb_vmware/base_config.py:269
msgid "{e} in section {sn!r} for VSphere {vs!r}:"
msgstr ""

#: lib/fb_vmware/base_config.py:275
msgid "There must be given at least the VSPhere hostname in section {sn!r} for VSphere {vs!r}."
msgstr ""

#: lib/fb_vmware/base_config.py:407
msgid "Empty VSphere name found."
msgstr ""

#: lib/fb_vmware/cluster.py:263 lib/fb_vmware/controller.py:187 lib/fb_vmware/datastore.py:352
#: lib/fb_vmware/dc.py:127 lib/fb_vmware/disk.py:274 lib/fb_vmware/ds_cluster.py:194
#: lib/fb_vmware/ether.py:305 lib/fb_vmware/host.py:549 lib/fb_vmware/host_port_group.py:161
#: lib/fb_vmware/network.py:211 lib/fb_vmware/obj.py:273 lib/fb_vmware/vm.py:470
msgid "Comparing {} objects ..."
msgstr ""

#: lib/fb_vmware/cluster.py:314
msgid "Cluster {c!r} has network {n!r}."
msgstr ""

#: lib/fb_vmware/cluster.py:321
msgid "Cluster {c!r} has datastore {d!r}."
msgstr ""

#: lib/fb_vmware/cluster.py:353 lib/fb_vmware/cluster.py:360
msgid "The given parameter {p!r} on calling method {m}() is not a sequence type."
msgstr ""

#: lib/fb_vmware/controller.py:56
msgid "Virtual IDE controller"
msgstr ""

#: lib/fb_vmware/controller.py:57
msgid "Virtual VNME controller"
msgstr ""

#: lib/fb_vmware/controller.py:58
msgid "Virtual PCI controller"
msgstr ""

#: lib/fb_vmware/controller.py:59
msgid "Virtual controller for keyboards and mice"
msgstr ""

#: lib/fb_vmware/controller.py:60
msgid "Virtual AHCI SATA controller"
msgstr ""

#: lib/fb_vmware/controller.py:61
msgid "Virtual SATA controller"
msgstr ""

#: lib/fb_vmware/controller.py:62
msgid "Virtual paravirtualized SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:63
msgid "Virtual BusLogic SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:64
msgid "Virtual LSI SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:65
msgid "Virtual LSI Logic SAS SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:66
msgid "Virtual SCSI controller"
msgstr ""

#: lib/fb_vmware/controller.py:67
msgid "Virtual Super IO Controller for floppy drives, parallel ports, and serial ports"
msgstr ""

#: lib/fb_vmware/controller.py:69
msgid "Virtual USB controller (USB 1.1 and 2.0)"
msgstr ""

#: lib/fb_vmware/controller.py:70
msgid "Virtual USB Extensible Host Controller Interface (USB 3.0)"
msgstr ""

#: lib/fb_vmware/controller.py:71
msgid "Unknown virtual controller"
msgstr ""

#: lib/fb_vmware/controller.py:275 lib/fb_vmware/ether.py:415 lib/fb_vmware/host.py:257
#: lib/fb_vmware/host.py:571 lib/fb_vmware/host_port_group.py:206 lib/fb_vmware/vm.py:494
msgid "Parameter {t!r} must be a {e}, {v!r} ({vt}) was given."
msgstr ""

#: lib/fb_vmware/controller.py:297
msgid "Checking class of controller: {!r}"
msgstr ""

#: lib/fb_vmware/controller.py:324 lib/fb_vmware/disk.py:435 lib/fb_vmware/ether.py:514
#: lib/fb_vmware/host_port_group.py:238 lib/fb_vmware/vm.py:644
msgid "Invalid type {t!r} as an item of a {c}, only {o} objects are allowed."
msgstr ""

#: lib/fb_vmware/controller.py:392 lib/fb_vmware/disk.py:503 lib/fb_vmware/ether.py:582
#: lib/fb_vmware/host.py:798 lib/fb_vmware/host_port_group.py:327 lib/fb_vmware/vm.py:712
msgid "{m} takes at most {max} arguments ({n} given)."
msgstr ""

#: lib/fb_vmware/controller.py:431
msgid "Controller is not in controller list."
msgstr ""

#: lib/fb_vmware/datastore.py:234 lib/fb_vmware/ds_cluster.py:138 lib/fb_vmware/iface.py:58
#: lib/fb_vmware/network.py:148 lib/fb_vmware/server.py:543
msgid "Parameter {t!r} must be a {e}, {v!r} was given."
msgstr ""

#: lib/fb_vmware/datastore.py:370 lib/fb_vmware/ds_cluster.py:212 lib/fb_vmware/network.py:229
msgid "Invalid item type {{!r}} to set, only {} allowed."
msgstr ""

#: lib/fb_vmware/datastore.py:372
msgid "The key {k!r} must be equal to the datastore name {n!r}."
msgstr ""

#: lib/fb_vmware/datastore.py:373 lib/fb_vmware/ds_cluster.py:215 lib/fb_vmware/network.py:232
msgid "None type as key is not allowed."
msgstr ""

#: lib/fb_vmware/datastore.py:374 lib/fb_vmware/ds_cluster.py:216 lib/fb_vmware/network.py:233
msgid "Empty key {!r} is not allowed."
msgstr ""

#: lib/fb_vmware/datastore.py:375 lib/fb_vmware/ds_cluster.py:217 lib/fb_vmware/network.py:234
#: lib/fb_vmware/obj.py:255 lib/fb_vmware/obj.py:264 lib/fb_vmware/obj.py:284 lib/fb_vmware/obj.py:296
msgid "Object {{!r}} is not a {} object."
msgstr ""

#: lib/fb_vmware/datastore.py:607
msgid "Could not handle datastore type {!r}."
msgstr ""

#: lib/fb_vmware/datastore.py:614
msgid "Could not found a datastore for {c:0.1f} GiB of type {t!r}."
msgstr ""

#: lib/fb_vmware/datastore.py:621
msgid "Searching datastore for {c:0.1f} GiB of type {t!r}."
msgstr ""

#: lib/fb_vmware/disk.py:543
msgid "Disk is not in disk list."
msgstr ""

#: lib/fb_vmware/ds_cluster.py:214
msgid "The key {k!r} must be equal to the datastore cluster name {n!r}."
msgstr ""

#: lib/fb_vmware/errors.py:38
msgid "No VSphere datastores found."
msgstr ""

#: lib/fb_vmware/errors.py:68
msgid "Invalid name {n!r} for a {o} VSphere object."
msgstr ""

#: lib/fb_vmware/errors.py:71
msgid "Invalid name {!r} for a VSphere object."
msgstr ""

#: lib/fb_vmware/errors.py:89
msgid "The VSphere datacenter {!r} is not existing."
msgstr ""

#: lib/fb_vmware/errors.py:105
msgid "The VSphere Virtual machine {!r} was not found."
msgstr ""

#: lib/fb_vmware/errors.py:125
msgid "No SAN based datastore found with at least {m:0.0f} MiB == {g:0.1f} GiB available space found."
msgstr ""

#: lib/fb_vmware/errors.py:143
msgid "The network {!r} is not existing."
msgstr ""

#: lib/fb_vmware/errors.py:162
msgid "Could not connect to the vSphere host {h}:{p} as user {u!r}."
msgstr ""

#: lib/fb_vmware/errors.py:184
msgid "Timeout on creating VM {vm!r} after {to:0.1f} seconds."
msgstr ""

#: lib/fb_vmware/errors.py:187
msgid "Timeout on creating VM {!r}."
msgstr ""

#: lib/fb_vmware/errors.py:203
msgid "Invalid type of {!r} for a port of a VSPhere server"
msgstr ""

#: lib/fb_vmware/errors.py:227
msgid ""
"Invalid port number {port!r} for the VSphere server, PORT must be greater than zero and less or "
"equal to {max}."
msgstr ""

#: lib/fb_vmware/ether.py:443
msgid "Checking class of ethernet card: {!r}"
msgstr ""

#: lib/fb_vmware/ether.py:621
msgid "card is not in card list."
msgstr ""

#: lib/fb_vmware/host.py:348 lib/fb_vmware/vm.py:110
msgid "The name of the vsphere may not be empty."
msgstr ""

#: lib/fb_vmware/host.py:576
msgid "Host {!r} seems to be offline!"
msgstr ""

#: lib/fb_vmware/host.py:728
msgid "Invalid type {{t!r}} as an item of a {{c}}, only {} objects are allowed."
msgstr ""

#: lib/fb_vmware/host.py:837
msgid "host is not in host list."
msgstr ""

#: lib/fb_vmware/host_port_group.py:366
msgid "group is not in group list."
msgstr ""

#: lib/fb_vmware/iface.py:126
msgid "Invalid MAC address {!r} for interface given."
msgstr ""

#: lib/fb_vmware/network.py:71
msgid "Trying to get IPv4 network {n!r} -> {i!r}."
msgstr ""

#: lib/fb_vmware/network.py:78
msgid "Could not get IP network from network name {!r}."
msgstr ""

#: lib/fb_vmware/network.py:81
msgid "Network {!r} has no IP network assigned."
msgstr ""

#: lib/fb_vmware/network.py:87
msgid "Initialized network object:"
msgstr ""

#: lib/fb_vmware/network.py:231
msgid "The key {k!r} must be equal to the network name {n!r}."
msgstr ""

#: lib/fb_vmware/network.py:479
msgid "Searching VSphere network for address {} ..."
msgstr ""

#: lib/fb_vmware/network.py:485
msgid "Found network {n!r} for IP {i}."
msgstr ""

#: lib/fb_vmware/network.py:489
msgid "Could not find VSphere network for IP {}."
msgstr ""

#: lib/fb_vmware/network.py:492
msgid "Could not find VSphere network for IP addresses {}."
msgstr ""

#: lib/fb_vmware/obj.py:78
msgid "The type of a {} may not be None."
msgstr ""

#: lib/fb_vmware/obj.py:83 lib/fb_vmware/obj.py:106 lib/fb_vmware/obj.py:129
msgid "Invalid {w}.{p} {v!r}."
msgstr ""

#: lib/fb_vmware/obj.py:145
msgid "The name prefix of a {} may not be None."
msgstr ""

#: lib/fb_vmware/obj.py:149
msgid "Invalid name prefix {p!r} for a {o}."
msgstr ""

#: lib/fb_vmware/server.py:126
msgid "Trying to get some 'about' information from VSphere."
msgstr ""

#: lib/fb_vmware/server.py:141
msgid "Got a {c} on connecting to {h!r}: {e}."
msgstr ""

#: lib/fb_vmware/server.py:150
msgid "VSphere server version: {!r}"
msgstr ""

#: lib/fb_vmware/server.py:152
msgid "Found VSphere about-information:"
msgstr ""

#: lib/fb_vmware/server.py:157
msgid "Trying to get datacenter from VSphere ..."
msgstr ""

#: lib/fb_vmware/server.py:171
msgid "Found VSphere datacenter {!r}."
msgstr ""

#: lib/fb_vmware/server.py:173
msgid "Info about datacenter:"
msgstr ""

#: lib/fb_vmware/server.py:184
msgid "Trying to get all clusters from VSphere ..."
msgstr ""

#: lib/fb_vmware/server.py:208 lib/fb_vmware/server.py:213
msgid "Found clusters:"
msgstr ""

#: lib/fb_vmware/server.py:229 lib/fb_vmware/server.py:488
msgid "Found standalone host"
msgstr ""

#: lib/fb_vmware/server.py:231 lib/fb_vmware/server.py:490
msgid "Found cluster"
msgstr ""

#: lib/fb_vmware/server.py:232 lib/fb_vmware/server.py:491
msgid "host"
msgid_plural "hosts"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:233 lib/fb_vmware/server.py:492
msgid "CPU"
msgid_plural "CPUs"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:234 lib/fb_vmware/server.py:493
msgid "thread"
msgid_plural "threads"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:235 lib/fb_vmware/server.py:494
msgid "network"
msgid_plural "networks"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:236 lib/fb_vmware/server.py:495
msgid "datastore"
msgid_plural "datastores"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:237 lib/fb_vmware/server.py:496
msgid ""
"{on} {cl!r}, {h} {h_l}, {cpu} {cpu_l}, {thr} {t_l}, {mem:0.1f} GiB Memory, {net} {nw_l} and {ds}"
" {ds_l}."
msgstr ""

#: lib/fb_vmware/server.py:260
msgid "Trying to get all datastores from VSphere ..."
msgstr ""

#: lib/fb_vmware/server.py:283 lib/fb_vmware/server.py:285
msgid "Found datastores:"
msgstr ""

#: lib/fb_vmware/server.py:293
msgid "Datastore mappings:"
msgstr ""

#: lib/fb_vmware/server.py:308
msgid "Datastore {!r} seems to be local."
msgstr ""

#: lib/fb_vmware/server.py:314
msgid "Found datastore {ds!r} of type {t!r}, capacity {c:0.1f} GByte."
msgstr ""

#: lib/fb_vmware/server.py:323
msgid "Trying to get all datastore clusters from VSphere ..."
msgstr ""

#: lib/fb_vmware/server.py:347 lib/fb_vmware/server.py:350
msgid "Found datastore clusters:"
msgstr ""

#: lib/fb_vmware/server.py:352
msgid "No VSphere datastore clusters found."
msgstr ""

#: lib/fb_vmware/server.py:358
msgid "Datastore cluster mappings:"
msgstr ""

#: lib/fb_vmware/server.py:364 lib/fb_vmware/server.py:424
msgid "Found a {} child."
msgstr ""

#: lib/fb_vmware/server.py:382
msgid "Trying to get all networks from VSphere ..."
msgstr ""

#: lib/fb_vmware/server.py:404
msgid "Found one VSphere network."
msgid_plural "Found {n} VSphere networks."
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:408 lib/fb_vmware/server.py:410
msgid "Found VSphere networks:"
msgstr ""

#: lib/fb_vmware/server.py:412
msgid "No VSphere networks found."
msgstr ""

#: lib/fb_vmware/server.py:418
msgid "Network mappings:"
msgstr ""

#: lib/fb_vmware/server.py:442
msgid "Trying to get all host systems from VSphere ..."
msgstr ""

#: lib/fb_vmware/server.py:469 lib/fb_vmware/server.py:474
msgid "Found hosts:"
msgstr ""

#: lib/fb_vmware/server.py:480
msgid "Checking {o}-object in cluster {c!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:507
msgid "Found host {h!r} in cluster {c!r}."
msgstr ""

#: lib/fb_vmware/server.py:522
msgid "Searching for VM {n!r} (pattern: {p!r}) in VSPhere {v!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:530
msgid "VSphere VM {!r} not found."
msgstr ""

#: lib/fb_vmware/server.py:632
msgid "Parameter {p!r} => {r!r} seems not to be a regex object."
msgstr ""

#: lib/fb_vmware/server.py:636
msgid "Parameter {p1!r} and {p2!r} may not be {w!r} at the same time."
msgstr ""

#: lib/fb_vmware/server.py:640
msgid "Trying to get list of VMs with name pattern {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:660
msgid "Searching in path {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:673
msgid "Found one VM with pattern {p!r}."
msgid_plural "Found {no} VMs with pattern {p!r}."
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:708
msgid "Checking VM {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:711
msgid "Checking VM {!r} for being a template ..."
msgstr ""

#: lib/fb_vmware/server.py:713
msgid "Checking VM {!r} for being not a template ..."
msgstr ""

#: lib/fb_vmware/server.py:721
msgid "Checking VM {!r} for pattern."
msgstr ""

#: lib/fb_vmware/server.py:724
msgid "Found VM {!r}."
msgstr ""

#: lib/fb_vmware/server.py:788
msgid "VM {!r} is already powered on."
msgstr ""

#: lib/fb_vmware/server.py:791
msgid "Powering on VM {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:795
msgid "VM {!r} successful powered on."
msgstr ""

#: lib/fb_vmware/server.py:819
msgid "VM {!r} is already powered off."
msgstr ""

#: lib/fb_vmware/server.py:822
msgid "Powering off VM {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:826
msgid "VM {!r} successful powered off."
msgstr ""

#: lib/fb_vmware/server.py:834
msgid "Ensuring existence of VSphere VM folders:"
msgstr ""

#: lib/fb_vmware/server.py:851
msgid "Trying to get VM folder object for path {!r}."
msgstr ""

#: lib/fb_vmware/server.py:876
msgid "Checking single VM folder {i}: {f!r}."
msgstr ""

#: lib/fb_vmware/server.py:887
msgid "Found VM folder {n}, parent: {p}"
msgstr ""

#: lib/fb_vmware/server.py:905
msgid "Ensuring existence of VSphere VM folder {!r}."
msgstr ""

#: lib/fb_vmware/server.py:930
msgid "VM Folder {!r} already exists."
msgstr ""

#: lib/fb_vmware/server.py:932
msgid "Creating VM folder {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:934
msgid "Simulation mode, don't creating it."
msgstr ""

#: lib/fb_vmware/server.py:950
msgid "Waiting for tasks to finish ..."
msgstr ""

#: lib/fb_vmware/server.py:962
msgid "Waiting at most {m} seconds for tasks {t} to finish ..."
msgstr ""

#: lib/fb_vmware/server.py:965
msgid "Waiting for tasks {} to finish ..."
msgstr ""

#: lib/fb_vmware/server.py:985
msgid "Waiting ..."
msgstr ""

#: lib/fb_vmware/server.py:1019
msgid "Creating VM {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:1022
msgid "Simulation mode - VM {!r} will not be created."
msgstr ""

#: lib/fb_vmware/server.py:1040
msgid "Generating create spec for VM {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:1048
msgid "Datastore path: {!r}"
msgstr ""

#: lib/fb_vmware/server.py:1051
msgid "VM path name: {!r}"
msgstr ""

#: lib/fb_vmware/server.py:1101
msgid "Generated VM config:"
msgstr ""

#: lib/fb_vmware/server.py:1110
msgid "Given disksize {!r} must be greater than zero."
msgstr ""

#: lib/fb_vmware/server.py:1123
msgid "There may be created at most 6 disks, but {} were given."
msgstr ""

#: lib/fb_vmware/server.py:1137
msgid "Generating spec for SCSI controller and one disk: {d}"
msgid_plural "Generating spec for SCSI controller and {n} disks: {d}"
msgstr[0] ""
msgstr[1] ""

#: lib/fb_vmware/server.py:1140
msgid "Generating spec for SCSI controller without disks."
msgstr ""

#: lib/fb_vmware/server.py:1165
msgid "Adding spec for disk {n!r} with {gb} GiB => {kb} KiByte."
msgstr ""

#: lib/fb_vmware/server.py:1200
msgid "Invalid Interface description {!r} given."
msgstr ""

#: lib/fb_vmware/server.py:1211
msgid "Defined interface:"
msgstr ""

#: lib/fb_vmware/server.py:1215
msgid "Adding spec for network interface {d!r} (Network {n!r}, MAC: {m!r}, summary: {s!r})."
msgstr ""

#: lib/fb_vmware/server.py:1267
msgid "Purging VM {!r} ..."
msgstr ""

#: lib/fb_vmware/server.py:1271
msgid "VM {!r} successful removed."
msgstr ""

#: lib/fb_vmware/server.py:1302
msgid "Did not found virtual ethernet device No. {no} (found {count} devices)."
msgstr ""

#: lib/fb_vmware/server.py:1321
msgid "Changes of MAC address:"
msgstr ""

#: lib/fb_vmware/server.py:1325
msgid "Successful changed MAC address of VM {v!r} to {m!r}."
msgstr ""

#: lib/fb_vmware/vm.py:573
msgid "Unknown hardware device of type {}."
msgstr ""

#: lib/fb_vmware/vm.py:576
msgid "There is something wrong wit VM {n!r} in cluster {c!r} and path {p!r} ..."
msgstr ""

#: lib/fb_vmware/vm.py:751
msgid "VM is not in VM list."
msgstr ""

#: lib/fb_vmware/xlate.py:98
msgid "Module directory:"
msgstr ""

#: lib/fb_vmware/xlate.py:99
msgid "Base directory:"
msgstr ""

#: lib/fb_vmware/xlate.py:100
msgid "Locale directory:"
msgstr ""

#: lib/fb_vmware/xlate.py:101
msgid "Locale domain:"
msgstr ""

#: lib/fb_vmware/xlate.py:102
msgid "Found .mo-file:"
msgstr ""

